export const paths = {
  room: (roomId) => `rooms/${roomId}`,
  roomMeta: (roomId) => `rooms/${roomId}/meta`,
  roomPlayers: (roomId) => `rooms/${roomId}/players`,
  roomPlayer: (roomId, uid) => `rooms/${roomId}/players/${uid}`,
  roomTokens: (roomId) => `rooms/${roomId}/tokens`,
  roomToken: (roomId, tokenId) => `rooms/${roomId}/tokens/${tokenId}`,
  roomSheets: (roomId) => `rooms/${roomId}/sheets`,
  roomSheet: (roomId, sheetId) => `rooms/${roomId}/sheets/${sheetId}`,
  roomRolls: (roomId) => `rooms/${roomId}/rolls`,
  roomMap: (roomId) => `rooms/${roomId}/map`,
  roomMapFog: (roomId) => `rooms/${roomId}/map/fog`,
  roomMapFogRects: (roomId) => `rooms/${roomId}/map/fog/rects`,
  roomMapView: (roomId) => `rooms/${roomId}/map/view`,
};
